Document: pcloudfs
Title: Debian pcloudfs Manual
Author: <insert document author here>
Abstract: This manual describes what pcloudfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pcloudfs/pfs.sgml.gz

Format: postscript
Files: /usr/share/doc/pcloudfs/pfs.ps.gz

Format: text
Files: /usr/share/doc/pcloudfs/pfs.text.gz

Format: HTML
Index: /usr/share/doc/pcloudfs/html/index.html
Files: /usr/share/doc/pcloudfs/html/*.html
